config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  resources :submodels
  resources :models
  resources :companies
  resources :venues
  resources :attractions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # 
  if defined? ::Avo
    Avo::Engine.routes.draw do
      get "companies/models", to: "companies#models"
      get "companies/models/submodels", to: "companies#submodels"
      get "waste_time", to: "tools#waste_time"
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  belongs_to :venue
  has_many :companyables, as: :companyable
  has_many :companies, through: :companyables

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/coaster.rb
class Coaster < Attraction

end

app/models/company.rb
class Company < ApplicationRecord
  has_many :companyables
  has_many :attractions, through: :companyables, source: :companyable, source_type: 'Attraction'
  has_many :venues, through: :companyables, source: :companyable, source_type: 'Venue'
  has_many :models
end

app/models/companyable.rb
class Companyable < ApplicationRecord
  belongs_to :company
  belongs_to :companyable, polymorphic: true
  belongs_to :model, optional: true
  belongs_to :submodel, optional: true
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :company
  has_many :submodels
  has_many :companyables, foreign_key: :model_id, dependent: :nullify
end

app/models/submodel.rb
class Submodel < ApplicationRecord
  belongs_to :model
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :attractions, dependent: :nullify
  has_many :companyables, as: :companyable
  has_many :companies, through: :companyables
end

app/controllers/avo/models_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::ModelsController < Avo::ResourcesController
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @models = Model.all
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy!

    respond_to do |format|
      format.html { redirect_to models_path, status: :see_other, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.require(:model).permit(:name, :company_id)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_with(model: model) do |form| %>
  <% if model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :company_id, style: "display: block" %>
    <%= form.text_field :company_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div id="<%= dom_id model %>">
  <p>
    <strong>Name:</strong>
    <%= model.name %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= model.company_id %>
  </p>

</div>

app/views/models/edit.html.erb
<% content_for :title, "Editing model" %>

<h1>Editing model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Show this model", @model %> |
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Models" %>

<h1>Models</h1>

<div id="models">
  <% @models.each do |model| %>
    <%= render model %>
    <p>
      <%= link_to "Show this model", model %>
    </p>
  <% end %>
</div>

<%= link_to "New model", new_model_path %>

app/views/models/new.html.erb
<% content_for :title, "New model" %>

<h1>New model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this model", edit_model_path(@model) %> |
  <%= link_to "Back to models", models_path %>

  <%= button_to "Destroy this model", @model, method: :delete %>
</div>