config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  resources :submodels
  resources :models
  resources :companies
  resources :venues
  resources :attractions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # 
  if defined? ::Avo
    Avo::Engine.routes.draw do
      get "companies/models", to: "companies#models"
      get "companies/models/submodels", to: "companies#submodels"
      get "waste_time", to: "tools#waste_time"
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/submodel.rb
class Submodel < ApplicationRecord
  belongs_to :model
end

app/controllers/avo/submodels_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::SubmodelsController < Avo::ResourcesController
end

app/controllers/submodels_controller.rb
class SubmodelsController < ApplicationController
  before_action :set_submodel, only: %i[ show edit update destroy ]

  # GET /submodels or /submodels.json
  def index
    @submodels = Submodel.all
  end

  # GET /submodels/1 or /submodels/1.json
  def show
  end

  # GET /submodels/new
  def new
    @submodel = Submodel.new
  end

  # GET /submodels/1/edit
  def edit
  end

  # POST /submodels or /submodels.json
  def create
    @submodel = Submodel.new(submodel_params)

    respond_to do |format|
      if @submodel.save
        format.html { redirect_to @submodel, notice: "Submodel was successfully created." }
        format.json { render :show, status: :created, location: @submodel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submodels/1 or /submodels/1.json
  def update
    respond_to do |format|
      if @submodel.update(submodel_params)
        format.html { redirect_to @submodel, notice: "Submodel was successfully updated." }
        format.json { render :show, status: :ok, location: @submodel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submodels/1 or /submodels/1.json
  def destroy
    @submodel.destroy!

    respond_to do |format|
      format.html { redirect_to submodels_path, status: :see_other, notice: "Submodel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submodel
      @submodel = Submodel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submodel_params
      params.require(:submodel).permit(:name, :model_id)
    end
end

app/helpers/submodels_helper.rb
module SubmodelsHelper
end

app/views/submodels/_form.html.erb
<%= form_with(model: submodel) do |form| %>
  <% if submodel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submodel.errors.count, "error") %> prohibited this submodel from being saved:</h2>

      <ul>
        <% submodel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :model_id, style: "display: block" %>
    <%= form.text_field :model_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/submodels/_submodel.html.erb
<div id="<%= dom_id submodel %>">
  <p>
    <strong>Name:</strong>
    <%= submodel.name %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= submodel.model_id %>
  </p>

</div>

app/views/submodels/edit.html.erb
<% content_for :title, "Editing submodel" %>

<h1>Editing submodel</h1>

<%= render "form", submodel: @submodel %>

<br>

<div>
  <%= link_to "Show this submodel", @submodel %> |
  <%= link_to "Back to submodels", submodels_path %>
</div>

app/views/submodels/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Submodels" %>

<h1>Submodels</h1>

<div id="submodels">
  <% @submodels.each do |submodel| %>
    <%= render submodel %>
    <p>
      <%= link_to "Show this submodel", submodel %>
    </p>
  <% end %>
</div>

<%= link_to "New submodel", new_submodel_path %>

app/views/submodels/new.html.erb
<% content_for :title, "New submodel" %>

<h1>New submodel</h1>

<%= render "form", submodel: @submodel %>

<br>

<div>
  <%= link_to "Back to submodels", submodels_path %>
</div>

app/views/submodels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @submodel %>

<div>
  <%= link_to "Edit this submodel", edit_submodel_path(@submodel) %> |
  <%= link_to "Back to submodels", submodels_path %>

  <%= button_to "Destroy this submodel", @submodel, method: :delete %>
</div>