config/routes.rb
Rails.application.routes.draw do
  mount Avo::Engine, at: Avo.configuration.root_path
  resources :submodels
  resources :models
  resources :companies
  resources :venues
  resources :attractions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # 
  if defined? ::Avo
    Avo::Engine.routes.draw do
      get "companies/models", to: "companies#models"
      get "companies/models/submodels", to: "companies#submodels"
      get "waste_time", to: "tools#waste_time"
    end
  end

  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: %i[ show edit update destroy ]

  # GET /attractions or /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1 or /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions or /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: "Attraction was successfully created." }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1 or /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: "Attraction was successfully updated." }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1 or /attractions/1.json
  def destroy
    @attraction.destroy!

    respond_to do |format|
      format.html { redirect_to attractions_path, status: :see_other, notice: "Attraction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attraction_params
      params.require(:attraction).permit(:name, :venue_id)
    end
end

app/controllers/avo/attractions_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::AttractionsController < Avo::ResourcesController
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_attraction.html.erb
<div id="<%= dom_id attraction %>">
  <p>
    <strong>Name:</strong>
    <%= attraction.name %>
  </p>

  <p>
    <strong>Venue:</strong>
    <%= attraction.venue_id %>
  </p>

</div>

app/views/attractions/_form.html.erb
<%= form_with(model: attraction) do |form| %>
  <% if attraction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
        <% attraction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :venue_id, style: "display: block" %>
    <%= form.text_field :venue_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<% content_for :title, "Editing attraction" %>

<h1>Editing attraction</h1>

<%= render "form", attraction: @attraction %>

<br>

<div>
  <%= link_to "Show this attraction", @attraction %> |
  <%= link_to "Back to attractions", attractions_path %>
</div>

app/views/attractions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Attractions" %>

<h1>Attractions</h1>

<div id="attractions">
  <% @attractions.each do |attraction| %>
    <%= render attraction %>
    <p>
      <%= link_to "Show this attraction", attraction %>
    </p>
  <% end %>
</div>

<%= link_to "New attraction", new_attraction_path %>

app/views/attractions/new.html.erb
<% content_for :title, "New attraction" %>

<h1>New attraction</h1>

<%= render "form", attraction: @attraction %>

<br>

<div>
  <%= link_to "Back to attractions", attractions_path %>
</div>

app/views/attractions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attraction %>

<div>
  <%= link_to "Edit this attraction", edit_attraction_path(@attraction) %> |
  <%= link_to "Back to attractions", attractions_path %>

  <%= button_to "Destroy this attraction", @attraction, method: :delete %>
</div>